name: Docker Image Airflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sandhujag/airflow:1.10.2
#      run: docker build . --file Dockerfile --build-arg AIRFLOW_DEPS="kubernetes" --tag sandhujag/airflow:1.10.12
#      working-directory: spark-hadoop-docker
      
    - name: Docker push
      run: docker push sandhujag/airflow:1.10.2
#      working-directory: spark-hadoop-docker
